mongodb:
  image: mongo:latest
  replicas: "1"
  port: 27017

webApp:
  image: fazakasabel/web-app:1.1.0
  replicas: "1"
  port: 3000

flaskApp:
  image: fazakasabel/flask-app:0.2.0
  replicas: "1"
  port: 5000
  
service:
  mongoPort: 27017
  webPort: 3000
  flaskPort: 5000

storage:
  id:   
  pvcName: efs-claim-1
  storageClassName: efs-sc

ingress:
  enabled: true
  className: nginx
