apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.flaskPort }}
    targetPort: {{ .Values.service.flaskPort }}
