apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongo"
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
          - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - name: persistent-storage
              mountPath: /data/db
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvcName }}
