apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.webPort }}
    targetPort: {{ .Values.webApp.port }}
