apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.service.mongoPort }}
    targetPort: {{ .Values.service.mongoPort }}
