apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: {{ .Values.webApp.replicas }}
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: {{ .Values.webApp.image }}
        ports:
        - containerPort: {{ .Values.webApp.port }}
